### ISSUE TITLE
[테스트팀] 팀 등록

### ISSUE THREAD

**Issue by dmin1325** [Dongguk-Developer/2024_hackathon_workshop#1]
### 팀명

테스트팀

### 팀장 이메일

test

### 팀장 깃허브 주소

test

### 팀원 1 이메일

test

### 팀원 1 깃허브 주소

test

### 팀원 2 이메일

test

### 팀원 2 깃허브 주소

test

**Comment by kdmin1325** [comment]
팀 빌딩을 축하드립니다.
본선에서 뵙겠습니다.

**Comment by kdmin1325** [comment]
팀 빌딩을 축하드립니다.
본선에서 뵙겠습니다.

**Comment by kdmin1325** [comment]
테스트팀
