### ISSUE TITLE
[솔리온] 팀 등록

### ISSUE THREAD

**Issue by seho0726** [Dongguk-Developer/2024_hackathon_workshop#10]
### 팀명

솔리온

### 팀장 이메일

sh2607@naver.com

### 팀장 깃허브 주소

https://github.com/seho0726

### 팀원 1 이메일

aa2001v@naver.com

### 팀원 1 깃허브 주소

https://github.com/Chan-bin01

### 팀원 2 이메일

klet777@naver.com

### 팀원 2 깃허브 주소

https://github.com/MRK777-GOGO

**Comment by kdmin1325** [comment]
환영합니다.
오세호 팀장님
임찬빈, 김용덕 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
