### ISSUE TITLE
[평균나이 19.3]

### ISSUE THREAD

**Issue by specializard** [Dongguk-Developer/2024_hackathon_workshop#12]
### 팀명

평균나이 19.3

### 팀장 이메일

rkdtkddyd2@gmail.com

### 팀장 깃허브 주소

 https://github.com/specializard

### 팀원 1 이메일

jeonghwanjang962@gmail.com

### 팀원 1 깃허브 주소

 https://github.com/wjdghks1004

### 팀원 2 이메일

sevenme2005@naver.com

### 팀원 2 깃허브 주소

https://github.com/hhs116

**Comment by kdmin1325** [comment]
팀이름 형식을 다시 확인해주세요.
[**팀이름**] 팀등록

*은 지우고 작성
