### ISSUE TITLE
[평균나이 19.3] 팀 등록

### ISSUE THREAD

**Issue by specializard** [Dongguk-Developer/2024_hackathon_workshop#14]
### 팀명

평균나이 19.3

### 팀장 이메일

rkdtkddyd2@gmail.com

### 팀장 깃허브 주소

https://github.com/specializard

### 팀원 1 이메일

jeonghwanjang962@gmail.com

### 팀원 1 깃허브 주소

https://github.com/wjdghks1004

### 팀원 2 이메일

sevenme2005@naver.com

### 팀원 2 깃허브 주소

https://github.com/hhs116

**Comment by kdmin1325** [comment]
안녕하세요.
강상용 팀장님
장정환, 이한샘 팀원님

팀빌딩을 축하드립니다.
