### ISSUE TITLE
[3전1안] 팀 등록

### ISSUE THREAD

**Issue by jinjerry0927** [Dongguk-Developer/2024_hackathon_workshop#2]
### 팀명

3전1안

### 팀장 이메일

jinuk.james.lee@gmail.com

### 팀장 깃허브 주소

jinjerry0927

### 팀원 1 이메일

ckdgur1241@naver.com

### 팀원 1 깃허브 주소

ckdgur1241

### 팀원 2 이메일

slewondr02@gmail.com

### 팀원 2 깃허브 주소

TTARAM

### 팀원 3 이메일

kjb112316@naver.com

### 팀원 3 깃허브 주소

Kimjunbaek

**Comment by kdmin1325** [comment]
환영합니다.
이진욱 팀장님
안창혁, 임성준, 김준백 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
