### ISSUE TITLE
[200_OK] 팀 등록

### ISSUE THREAD

**Issue by minnnisu** [Dongguk-Developer/2024_hackathon_workshop#3]
### 팀명

200_OK

### 팀장 이메일

mine52100@naver.com

### 팀장 깃허브 주소

https://github.com/minnnisu

### 팀원 1 이메일

kkr010128@icloud.com

### 팀원 1 깃허브 주소

https://github.com/kkr010128

### 팀원 2 이메일

DUKY8N@gmail.com

### 팀원 2 깃허브 주소

https://github.com/DUKY8N

### 팀원 3 이메일

2000tjdgns@naver.com

### 팀원 3 깃허브 주소

https://github.com/JSH0905

**Comment by kdmin1325** [comment]
팀 빌딩에 실패하였습니다.
대회 신청 시 등록한 이메일과 같은 이메일인지 확인해주세요.
