### ISSUE TITLE
[삼손할매] 팀 등록

### ISSUE THREAD

**Issue by Parkjimin03** [Dongguk-Developer/2024_hackathon_workshop#4]
### 팀명

삼손할매

### 팀장 이메일

jimin033172@naver.com

### 팀장 깃허브 주소

Parkjimin03

### 팀원 1 이메일

algospheredev@gmail.com

### 팀원 1 깃허브 주소

HaeminYoun

### 팀원 2 이메일

 s471547@naver.com

### 팀원 2 깃허브 주소

 SonjunAP

### 팀원 3 이메일

dlcoak@naver.com 

### 팀원 3 깃허브 주소

lee-chaemin

**Comment by kdmin1325** [comment]
팀빌딩에 실패하였습니다.
팀원의 깃허브 아이디(SonjunAP)를 다시 확인해주세요.
