### ISSUE TITLE
[자바조아] 팀 등록

### ISSUE THREAD

**Issue by mjgwon24** [Dongguk-Developer/2024_hackathon_workshop#5]
### 팀명

자바조아

### 팀장 이메일

alswlchlrh8@naver.com

### 팀장 깃허브 주소

https://github.com/mjgwon24

### 팀원 1 이메일

wowddok@gmail.com

### 팀원 1 깃허브 주소

https://github.com/wowddok99

### 팀원 2 이메일

lh7721004@naver.com

### 팀원 2 깃허브 주소

https://github.com/lh7721004

### 팀원 3 이메일

wole1115@naver.com

### 팀원 3 깃허브 주소

https://github.com/kavu-multi

**Comment by kdmin1325** [comment]
환영합니다.
권민지 팀장님
전상은, 김이현, 전형주 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
