### ISSUE TITLE
[200_OK] 팀 등록

### ISSUE THREAD

**Issue by minnnisu** [Dongguk-Developer/2024_hackathon_workshop#6]
### 팀명

200_OK

### 팀장 이메일

mine52100@naver.com

### 팀장 깃허브 주소

https://github.com/minnnisu

### 팀원 1 이메일

kkr010128@icloud.com

### 팀원 1 깃허브 주소

https://github.com/kkr010128

### 팀원 2 이메일

miso1061402ggm@gmail.com

### 팀원 2 깃허브 주소

https://github.com/DUKY8N

### 팀원 3 이메일

2000tjdgns@naver.com

### 팀원 3 깃허브 주소

https://github.com/JSH0905

**Comment by kdmin1325** [comment]
환영합니다.
최민수 팀장님
김광래, 임덕윤, 정성훈 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
