### ISSUE TITLE
[삼손할매] 팀 등록

### ISSUE THREAD

**Issue by Parkjimin03** [Dongguk-Developer/2024_hackathon_workshop#7]
### 팀명

삼손할매

### 팀장 이메일

jimin033172@naver.com

### 팀장 깃허브 주소

Parkjimin03

### 팀원 1 이메일

algospheredev@gmail.com

### 팀원 1 깃허브 주소

HaeminYoun

### 팀원 2 이메일

dlcoak@naver.com 

### 팀원 2 깃허브 주소

lee-chaemin

### 팀원 3 이메일

s471547@naver.com

### 팀원 3 깃허브 주소

SonJunYheok

**Comment by kdmin1325** [comment]
환영합니다.
박지민 팀장님
윤해민, 이채민, 손준혁 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
