### ISSUE TITLE
[null] 팀 등록

### ISSUE THREAD

**Issue by lce0517** [Dongguk-Developer/2024_hackathon_workshop#8]
### 팀명

null

### 팀장 이메일

ashaeun2010@naver.com

### 팀장 깃허브 주소

https://github.com/lce0517

### 팀원 1 이메일

suheon777@icloud.com

### 팀원 1 깃허브 주소

https://github.com/suheon927

### 팀원 2 이메일

gilbert0001@naver.com

### 팀원 2 깃허브 주소

https://github.com/leetae04kr

### 팀원 3 이메일

rest753321@gmail.com

### 팀원 3 깃허브 주소

https://github.com/LemonHater

**Comment by kdmin1325** [comment]
환영합니다.
임채은 팀장님
이수헌, 이태영, 김재윤 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
