### ISSUE TITLE
[요즘것들] 팀 등록

### ISSUE THREAD

**Issue by woohaharam** [Dongguk-Developer/2024_hackathon_workshop#9]
### 팀명

요즘것들

### 팀장 이메일

woo01051227040@dongguk.ac.kr

### 팀장 깃허브 주소

https://github.com/woohaharam

### 팀원 1 이메일

myidea1222@naver.com

### 팀원 1 깃허브 주소

https://github.com/ji-seong047

### 팀원 2 이메일

heyejin5245@naver.com

### 팀원 2 깃허브 주소

https://github.com/gjdPwls

### 팀원 3 이메일

yam3232@naver.com

### 팀원 3 깃허브 주소

https://github.com/haltang

**Comment by kdmin1325** [comment]
환영합니다.
우주영 팀장님
박지성, 허예진, 오원준 팀원님

해커톤 본선에서 뵙겠습니다.
팀빌딩을 축하합니다.
